adminUser:
  password: vault:ragnar/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: rverduci@cloudbees.com
  token: vault:ragnar/pipelineUser:token
  username: core-platform-test-bot
prow:
  hmacToken: vault:ragnar/prow:hmacToken
